// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKrcjBy5q2gQx1c1wvDqe88yqojRQ7Pw',
    appId: '1:287872030512:web:b2129a0d058fd69fc99af5',
    messagingSenderId: '287872030512',
    projectId: 'permitease-17df4',
    authDomain: 'permitease-17df4.firebaseapp.com',
    storageBucket: 'permitease-17df4.appspot.com',
    measurementId: 'G-ZMSBDXWY18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7IawmGJMdCH2IAVpWfEmVGfG6Gf0t2Q',
    appId: '1:287872030512:android:b1435194946319c6c99af5',
    messagingSenderId: '287872030512',
    projectId: 'permitease-17df4',
    storageBucket: 'permitease-17df4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1uv90bid13xtg56-fic33l_19eOY6_E',
    appId: '1:287872030512:ios:5b41d76a44bbbf83c99af5',
    messagingSenderId: '287872030512',
    projectId: 'permitease-17df4',
    storageBucket: 'permitease-17df4.appspot.com',
    iosBundleId: 'com.example.permitease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1uv90bid13xtg56-fic33l_19eOY6_E',
    appId: '1:287872030512:ios:5b41d76a44bbbf83c99af5',
    messagingSenderId: '287872030512',
    projectId: 'permitease-17df4',
    storageBucket: 'permitease-17df4.appspot.com',
    iosBundleId: 'com.example.permitease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfKrcjBy5q2gQx1c1wvDqe88yqojRQ7Pw',
    appId: '1:287872030512:web:bcfbb47e8b42b76cc99af5',
    messagingSenderId: '287872030512',
    projectId: 'permitease-17df4',
    authDomain: 'permitease-17df4.firebaseapp.com',
    storageBucket: 'permitease-17df4.appspot.com',
    measurementId: 'G-MR369TMYV9',
  );
}
